import { Printer, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PrescriptionPDFProps {
  prescriptionNumber: string;
  version: number;
  disease?: string;
  patientName: string;
  doctorName: string;
  hospital?: string;
  items: Array<{
    medicineName: string;
    dosage: string;
    frequency: string;
    timing?: string;
    anupana?: string;
    duration: string;
    instructions?: string;
    isAyurvedic?: boolean;
  }>;
  notes?: string;
  createdAt: number;
}

export function PrescriptionPDF({
  prescriptionNumber,
  version,
  disease,
  patientName,
  doctorName,
  hospital = "RogiPatrika Health Center",
  items,
  notes,
  createdAt,
}: PrescriptionPDFProps) {
  const printPrescription = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Prescription ${prescriptionNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', serif; color: #1a1a1a; padding: 30px; max-width: 700px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 2px solid #1a1a1a; padding-bottom: 15px; margin-bottom: 20px; }
    .hospital-name { font-size: 22px; font-weight: bold; color: #1a4d2e; }
    .subtitle { font-size: 11px; color: #555; margin-top: 4px; }
    .rx-header { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 12px; }
    .rx-number { font-weight: bold; color: #1a4d2e; }
    .patient-info { background: #f5f5f5; padding: 12px; border-radius: 6px; margin-bottom: 15px; font-size: 13px; }
    .patient-info p { margin-bottom: 3px; }
    .disease { background: #fff3cd; padding: 8px 12px; border-radius: 6px; margin-bottom: 15px; font-size: 13px; font-weight: 500; }
    .rx-symbol { font-size: 28px; font-weight: bold; color: #1a4d2e; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 15px; font-size: 12px; }
    th { background: #1a4d2e; color: white; padding: 8px; text-align: left; }
    td { padding: 8px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f9f9f9; }
    .ayurvedic-badge { background: #d4edda; color: #155724; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
    .notes { background: #f5f5f5; padding: 10px; border-radius: 6px; margin-bottom: 20px; font-size: 12px; }
    .footer { border-top: 1px solid #ccc; padding-top: 10px; font-size: 11px; color: #666; display: flex; justify-content: space-between; }
    .signature { text-align: right; margin-top: 30px; }
    .signature-line { border-top: 1px solid #1a1a1a; width: 200px; margin-left: auto; margin-top: 40px; padding-top: 5px; font-size: 12px; }
    @media print { body { padding: 15px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="hospital-name">${hospital}</div>
    <div class="subtitle">Patient Case-Taking Software • Ministry of AYUSH (SIH 26047)</div>
  </div>

  <div class="rx-header">
    <div class="rx-number">${prescriptionNumber} ${version > 1 ? `(v${version})` : ""}</div>
    <div>${new Date(createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</div>
  </div>

  <div class="patient-info">
    <p><strong>Patient:</strong> ${patientName}</p>
    <p><strong>Prescriber:</strong> Dr. ${doctorName}</p>
  </div>

  ${disease ? `<div class="disease"><strong>Condition:</strong> ${disease}</div>` : ""}

  <div class="rx-symbol">℞</div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Medicine</th>
        <th>Dosage</th>
        <th>Frequency</th>
        <th>Timing</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      ${items
        .map(
          (item, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>
            ${item.medicineName}
            ${item.isAyurvedic ? '<span class="ayurvedic-badge">🌿 Ayurvedic</span>' : ""}
          </td>
          <td>${item.dosage}</td>
          <td>${item.frequency}</td>
          <td>${item.timing || "—"}</td>
          <td>${item.duration}</td>
        </tr>
        ${item.anupana || item.instructions ? `<tr><td colspan="6" style="font-size:11px;color:#555;border-bottom:2px solid #ddd;">${item.anupana ? `Anupana: ${item.anupana}` : ""} ${item.instructions ? `• ${item.instructions}` : ""}</td></tr>` : ""}
      `,
        )
        .join("")}
    </tbody>
  </table>

  ${notes ? `<div class="notes"><strong>Notes:</strong> ${notes}</div>` : ""}

  <div class="signature">
    <div class="signature-line">Dr. ${doctorName}</div>
  </div>

  <div class="footer">
    <div>Generated by RogiPatrika — SIH 26047</div>
    <div>AI-assisted — verify with healthcare professional</div>
  </div>
</body>
</html>`;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  };

  const downloadPDF = () => {
    // For browser printing/downloading
    printPrescription();
  };

  return (
    <div className="flex gap-2">
      <Button
        type="button"
        variant="outline"
        onClick={printPrescription}
        className="rounded-xl text-xs font-semibold border-[#E2E8F0] text-[#334155] hover:bg-[#F8FAFC]"
      >
        <Printer className="w-3.5 h-3.5 mr-1.5" /> Print Rx
      </Button>
      <Button
        type="button"
        variant="outline"
        onClick={downloadPDF}
        className="rounded-xl text-xs font-semibold border-[#E2E8F0] text-[#334155] hover:bg-[#F8FAFC]"
      >
        <Download className="w-3.5 h-3.5 mr-1.5" /> Download
      </Button>
    </div>
  );
}
